rvm:
  - "1.9.3"
  - "2.0"
before_install:
  - gem update --system 1.8.25
before_script:
  - ./populate_ymls.sh
  - psql -c 'create database myapp_test;' -U postgres; cp ./config/database.travis_yml ./config/database.yml
  - RAILS_ENV=test rake db:migrate
script:
  - bundle exec spec spec/models
gemfile:
  - Gemfile
#  - gemfiles/Gemfile.rails-3.x
